
--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Verbose generation: ON

-- note: spaces within table/column names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- To drop the tables generated by this script run -
--   'C:\Users\c7302796\OneDrive - Leeds Beckett University\DATA WAREHOUSE AND MODELLING APPROACHES\ASSESSMENT\Assessment 2\sql\assignment2_drop.sql'

--------------------------------------------------------------



--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.

-- Create a Database table to represent the "FACT_ENGAGEMENT" entity.
CREATE TABLE FACT_ENGAGEMENT(
	id_report	INTEGER NOT NULL,
	id_vle	INTEGER,
	id_time	INTEGER,
	avg_stdnt_egmt_per_resource	INTEGER,
	fk1_id_time	INTEGER NOT NULL,
	fk2_id_vle	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "FACT_ENGAGEMENT".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_FACT_ENGAGEMENT PRIMARY KEY (id_report)
);

-- Create a Database table to represent the "DIM_TIME" entity.
CREATE TABLE DIM_TIME(
	id_time	INTEGER NOT NULL,
	year	VARCHAR(8) NOT NULL,
	month	VARCHAR(8) NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "DIM_TIME".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_TIME PRIMARY KEY (id_time)
);

-- Create a Database table to represent the "DIM_VLE" entity.
CREATE TABLE DIM_VLE(
	id_vle	INTEGER NOT NULL,
	activity_type	VARCHAR(8),
	sum_click	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "DIM_VLE".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_VLE PRIMARY KEY (id_vle)
);


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "FACT_ENGAGEMENT_DIM_TIME" relationship

-- This constraint ensures that the foreign key of table "FACT_ENGAGEMENT"
-- correctly references the primary key of table "DIM_TIME"

ALTER TABLE FACT_ENGAGEMENT ADD CONSTRAINT fk1_FACT_ENGAGEMENT_to_DIM_TIME FOREIGN KEY(fk1_id_time) REFERENCES DIM_TIME(id_time) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "FACT_ENGAGEMENT_DIM_VLE" relationship

-- This constraint ensures that the foreign key of table "FACT_ENGAGEMENT"
-- correctly references the primary key of table "DIM_VLE"

ALTER TABLE FACT_ENGAGEMENT ADD CONSTRAINT fk2_FACT_ENGAGEMENT_to_DIM_VLE FOREIGN KEY(fk2_id_vle) REFERENCES DIM_VLE(id_vle) ON DELETE RESTRICT ON UPDATE RESTRICT;


--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------
